/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.IDao;
import entities.Machine;
import entities.Salle;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author grham
 */
public class SallesForm extends javax.swing.JInternalFrame {
    
    Salle salle;
    IDao<Salle> daoSalle = null;
    DefaultTableModel modelSalle = null;
    int column = 0;
    int SelectedSalleId = -1;

    /**
     * Creates new form SalleForm
     */
    public SallesForm() {
        initComponents();
         
        try {
            
            modelSalle = (DefaultTableModel) tbl_Salle.getModel();
            daoSalle = (IDao<Salle>) Naming.lookup("rmi://localhost:1099/Salle");
            
            loadGrid();
            
        } catch (NotBoundException ex) {
            Logger.getLogger(SallesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SallesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(SallesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    
    public void loadGrid(){
        try {
            modelSalle.setRowCount(0);
            for(Salle s : daoSalle.findAll())
                modelSalle.addRow(new Object[]{
                    s.getId(),
                    s.getCode()
                });
        } catch (RemoteException ex) {
            Logger.getLogger(MachinesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     
    public void fillForm(){
        try {
            // TODO add your handling code here:
            salle = null;
            salle = daoSalle.findById(SelectedSalleId);
            txtCode.setText(salle.getCode());
            
        } catch (RemoteException ex) {
            Logger.getLogger(MachinesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        edBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Salle = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des Salle");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des Salles"));

        jLabel1.setText("Code : ");

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        addBtn.setText("Ajouter");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Suprimer");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBtnActionPerformed(evt);
            }
        });

        edBtn.setText("Modifier");
        edBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBtnActionPerformed(evt);
            }
        });

        tbl_Salle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Salle.getTableHeader().setReorderingAllowed(false);
        tbl_Salle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Salle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(delBtn)
                                .addGap(5, 5, 5)
                                .addComponent(edBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addBtn)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delBtn)
                    .addComponent(edBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("Salles");
        getAccessibleContext().setAccessibleDescription("Salles");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void ajouterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtnActionPerformed
        // TODO add your handling code here:
        
        String code=txtCode.getText();
        
        if(code.isEmpty())
               JOptionPane.showMessageDialog(this,
                       "Merci de remplire le champ Code SVP!",
                       "Dialog",
                       JOptionPane.ERROR_MESSAGE);
        else{
            try {
                daoSalle.create(new Salle(code));
                loadGrid();
                txtCode.setText("");
                JOptionPane.showMessageDialog(this,
                        "Salle ajouter avec succès",
                        "Dialog",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (RemoteException ex) {
                Logger.getLogger(SallesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ajouterBtnActionPerformed

    private void supprimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            daoSalle.delete(daoSalle.findById(SelectedSalleId));
            JOptionPane.showMessageDialog(this,
                    "Salle supprimer avec succès", 
                    "Dialog",
                    JOptionPane.INFORMATION_MESSAGE);
            txtCode.setText("");
            loadGrid();
           
        } catch (RemoteException ex) {
            Logger.getLogger(MachinesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
    }//GEN-LAST:event_supprimerBtnActionPerformed

    private void tbl_SalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SalleMouseClicked
        // TODO add your handling code here:
        
        int row = tbl_Salle.getSelectedRow();
        SelectedSalleId = Integer.parseInt(tbl_Salle.getModel().getValueAt(row, column).toString()); 
        fillForm();
    }//GEN-LAST:event_tbl_SalleMouseClicked

    private void modifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBtnActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            salle = null;
            salle = daoSalle.findById(SelectedSalleId);
             
            salle.setCode(txtCode.getText());
            if("".equals(salle.getCode()))
                    JOptionPane.showMessageDialog(this,
                            "Merci de remplire les champ!",
                            "Dialog",
                            JOptionPane.ERROR_MESSAGE);

            else{
                daoSalle.update(salle);
                txtCode.setText("");
                loadGrid(); 
            }
        } catch (RemoteException ex) {
            Logger.getLogger(MachinesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
                   
    }//GEN-LAST:event_modifierBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton edBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Salle;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
